import type { StatusV2 } from "./lib/types.js";

export const submoduleStatusFixture = {
  schemaVersion: 2,
  toolVersion: "0.0.0",
  mode: "submodule",
  workspaceRoot: "/workspace",
  currentAlias: null,
  currentWorktree: null,
  currentTarget: null,
  root: {
    path: "/workspace",
    relation: "same",
    branch: "main",
    head: "0000000",
    detached: false,
    dirty: false,
    changes: { staged: 0, unstaged: 0, untracked: 0 },
    submodulePointers: { moved: [], staged: [], split: [], conflict: [] },
  },
  repos: [],
  errors: [],
} satisfies StatusV2;

export const worktreeStatusFixture = {
  schemaVersion: 2,
  toolVersion: "0.0.0",
  mode: "worktree",
  workspaceRoot: "/workspace",
  currentAlias: "api",
  currentWorktree: "main",
  currentTarget: "api/main",
  root: null,
  repos: [{
    mode: "worktree",
    alias: "api",
    commonPath: ".oms/repos/api.git",
    absoluteCommonPath: "/workspace/.oms/repos/api.git",
    ready: true,
    remotes: [{ name: "origin" }],
    worktrees: [{
      managed: true,
      name: "main",
      target: "api/main",
      path: "/workspace/oms/api/main",
      relativePath: "oms/api/main",
      branch: "main",
      head: "0000000",
      detached: false,
      trackingBranch: "origin/main",
      ahead: 0,
      behind: 0,
      dirty: false,
      changes: { staged: 0, unstaged: 0, untracked: 0 },
      locked: false,
      operation: null,
      error: null,
    }],
    error: null,
  }],
  errors: [],
} satisfies StatusV2;
